### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by ruben27813** [juanjoSanz/hass_wibeee#11]
I dont understand.

It doesent work, but i dont know if im doing well:
<hass_folder>/custom_components/sensor/wibeee.py
no wibee.py file...  there is a wibee dir and a sensor.py file.

it seems easy, but I cant get the device.

Thanks for help.

**Comment by luuuis** [comment]
You should place the custom components code under the path `<hass_folder>/custom_components/wibeee`. In the end you'll have `<hass_folder>/custom_components/wibeee/sensor.py`, as well as the other files in the same directory.
