### ISSUE TITLE
One Phase Support

### ISSUE THREAD

**Issue by juanjoSanz** [juanjoSanz/hass_wibeee#3]
Oscar modified the code to support one phase devices,

Entry in Home Assistant Communityhttps://community.home-assistant.io/t/new-integration-energy-monitoring-device-circutor-wibeee/45276/11

That code has been uploaded into a new branch
https://github.com/juanjoSanz/hass_wibeee/tree/one_phase

Current status: test code modification with different devices

**Comment by LSousa77** [comment]
That branch isn't available anymore...
