### ISSUE TITLE
HA 0.88+ new custom components structure

### ISSUE THREAD

**Issue by barto64** [juanjoSanz/hass_wibeee#5]
Would it be posible to accomodate new HA 0.88+ custom components set-up ? I am a super fan of Mirubee, I got it 2/3 uears ago and is unbelievable useful to monitor power consumption and optimizing it getting massive savings.

**Comment by juanjoSanz** [comment]
done, please check last commit

**Comment by juanjoSanz** [comment]
I realized it was partially fixed, it works but it should be changed to use __init__.py file

**Comment by juanjoSanz** [comment]
closed due to new breaking change at HA 0.95
