### ISSUE TITLE
Error with scan interval

### ISSUE THREAD

**Issue by abacao** [juanjoSanz/hass_wibeee#7]
Hello,

I'm using the example and I have the following error:

```
Invalid config for [sensor.wibeee]: expected int for dictionary value @ data['scan_interval']. Got datetime.timedelta(seconds=15). (See ?, line ?). 
```

What am I doing wrong?

The default values seem to break the use of the wibeee app (box gets disconnected if I use the API too much?)

**Comment by abacao** [comment]
I really think I am seeing a pattern here.
My mirubee box goes offline if I use this integration.
The information on the app is that the meter is disconnected.
If I stop using, it seems to come back alive.
Anyone experiencing this?

**Comment by pacoja84** [comment]
Hello @abacao ,
you can edit manually the file: sensor.py 
in the line 87 you have the time hardcoded:

SCAN_INTERVAL = timedelta(seconds=1)

Change it for the value that you want. For example 30 segs:

SCAN_INTERVAL = timedelta(seconds=30)

Hope it helps.

**Comment by abacao** [comment]
Hello @pacoja84,

I have already solved it.

You can see my fork at https://github.com/abacao/hass_wibeee
