### ISSUE TITLE
Solar Production on wibeee

### ISSUE THREAD

**Issue by LSousa77** [juanjoSanz/hass_wibeee#8]
Hi. I have an Solar system on my house and if the production it's bigger than the comsumption the result appears as compuption instead negative. As i can see the " <fase1_factor_potencia>-0.684</fase1_factor_potencia> " it's negative when the production it's bigger than the consumption. That's te rreasun on Wibeee appears negative values.
I neeed a negative value to create routines and scenes (activate an boiler qhen production it's bigger thatn consumption).
Any help?

Regards

**Comment by luuuis** [comment]
Check out [SENSOR_EXAMPLES.md](https://github.com/luuuis/hass_wibeee/blob/8dd6f804cb427df90b7a151c48ac05b6999d0b85/SENSOR_EXAMPLES.md#power-sensors), there is a section on how to do this using template sensors.
